doo/scanbot-sdk-maui-example

- ScanbotSDKMAUIExample/DocumentSDK.NET.Droid/AndroidManifest.xml
- ScanbotSDKMAUIExample/DocumentSDK.NET.Droid/DocumentSDK.NET.Droid.csproj
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Models/SDKOperations.cs
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Pages/HomePage.xaml
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Pages/HomePage.xaml.cs
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Pages/ImageResultsPage.cs
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Platforms/Android/AndroidManifest.xml
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/Platforms/iOS/Info.plist
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/ScanbotSDK.MAUI.csproj
- ScanbotSDKMAUIExample/ScanbotSDK.MAUI/ViewModels/HomePageViewModel.cs
- ScanbotSDKMAUIExample/ScanbotSDK.NET.iOS/Platforms/iOS/Controller/ImageListController.cs
- ScanbotSDKMAUIExample/ScanbotSDK.NET.iOS/Platforms/iOS/Controller/MainViewController.cs
- ScanbotSDKMAUIExample/ScanbotSDK.NET.iOS/ScanbotSDK.NET.iOS.csproj
- ScanbotSDKMAUIExample/clean.sh
> MAUI Acceptance 2.2.0 Public Example

- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/ViewModels/HomePageViewModel.cs
- ScanbotSDKExamples/NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- ScanbotSDKExamples/NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
Latest beta update to fix SelectionOveralyConfiguration naming so that I could then add names to the intialisation of the object (which also makes it consistent with batch barcode scanning).
> Updated version to latest beta

- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/layout/fragment_barcode_dialog.xml
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/values/strings.xml
> [EPIC 3739] RTU UI - NET Droid.

- ScanbotSDKExamples/NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- ScanbotSDKExamples/NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/Controller/MainViewController.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/Controller/PopupController.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/View/FilterView.cs
- Added Medical certificate scanner example in the RTU UI iOS Example.
> NET: Added Medical Certificate example.

- Libraries.txt
- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/Handlers/BarcodeCameraViewHandler.Android.cs
- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/Platforms/iOS/CustomViews/BarcodeCameraView_iOS.cs
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/Pages/HomePage.BarcodeDetector.xaml.cs
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/Pages/ImageDetailPage.cs
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- ScanbotSDKExamples/NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- ScanbotSDKExamples/NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
**Improvements:**
- Privacy Manifest added in the under-the-hood iOS SDK
**Bug Fixes:**
- **iOS:** Cropping issue fixed
> iOS SDK Update

- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/Handlers/BarcodeCameraViewHandler.Android.cs
- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/Platforms/iOS/CustomViews/BarcodeCameraView_iOS.cs
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- ScanbotSDKExamples/NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- ScanbotSDKExamples/NET/ClassicComponent.Droid/MainActivity.cs
- ScanbotSDKExamples/NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/PagePreviewActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
* ClassicComponent Maui:
- Added validations to handle optional values for the AR overlay.
* NET Droids:
- Used an existing app-level flag to check encryption enable/disable.
- Used Document URL instead of Document Preview Url in Droid.
> ClassicComponent - Maui - AR Overlay

- ScanbotSDKExamples/NET/ClassicComponent.Droid/Activities/CameraXViewDemoActivity.cs
- ScanbotSDKExamples/NET/ClassicComponent.Droid/Activities/CroppingImageDemoActivity.cs
- ScanbotSDKExamples/NET/ClassicComponent.Droid/MainActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/BaseResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/PageFilterActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/PagePreviewActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V1/BarcodeResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V1/DetailedItemDataActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V2/BarcodeResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V2/DetailedItemDataActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/MainActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Model/BaseBarcodeResult.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/layout/activity_main.xml
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/layout/barcode_result.xml
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/layout/detailed_item_data.xml
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/ActionBarConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/ArOverlayUseCaseSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/ItemMappingConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/MultipleScanningPreviewConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/MultipleScanningUseCaseSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/PaletteConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/SingleScanningUseCaseSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/TopBarConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Snippets/UserGuidanceConfigSnippet.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Utils/ImageUtils.cs
- Updated the NET examples to v5.0 SDK
- Rebased with the current branch before PR
> NET Projects update to 5.0

- ScanbotSDKExamples/MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/Pages/ImageResultsPage.cs
- ScanbotSDKExamples/MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- RTU UI: Updated the OCR handling code as per the latest changes in 4.2.1 hotfix.
- Updated the 4.2.1-RC.1 package to the MAUI projects
> [EPIC-4627] - MAUI OCR Hotfix

- ScanbotSDKExamples/NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- ScanbotSDKExamples/NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/BaseResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V1/BarcodeResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V2/BarcodeResultActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Activities/V2/DetailedItemDataActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/MainActivity.BarcodeRTUv2.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/MainActivity.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- ScanbotSDKExamples/NET/ReadyToUseUI.Droid/Resources/layout/detailed_item_data.xml
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/Controller/BarcodeResultDetailsController.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/Controller/BarcodeResultListController.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/Controller/MainViewController.BarcodeRTUv2.cs
- ScanbotSDKExamples/NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
- Updated the code snippets and UI for iOS and Android
- Added the result page for iOS barcode V2 results
- Fixed UI issue for Android BarcodeResultDetails page
- Commented the Android packages which are conflicting and are lower version compared to the SDKs
- Removed the net7.0-android and net7.0-ios targets due to issue while running on JetBrains.Rider IDE
> NET - RTU UI - Example project Update to 5.1

- NET/ReadyToUseUI.Droid/MainActivity.cs
- Fixed the result popup for License Plate scanner
> [EPIC-4886] NET DS: Droid - License Plate result

- NET/ReadyToUseUI.Droid/Activities/BaseResultActivity.cs
- NET/ReadyToUseUI.Droid/Activities/V1/BarcodeResultActivity.cs
- NET/ReadyToUseUI.Droid/Activities/V2/BarcodeResultActivity.cs
- NET/ReadyToUseUI.Droid/MainActivity.DataDetector.cs
- NET/ReadyToUseUI.Droid/MainActivity.cs
- NET/ReadyToUseUI.Droid/Resources/layout/barcode_result.xml
- NET/ReadyToUseUI.iOS/Controller/ImageListController.cs
- NET/ReadyToUseUI.iOS/Controller/MainViewController.DataDetectors.cs
- NET/ReadyToUseUI.iOS/Controller/MainViewController.cs
- Fixed naming for Recognise to Recognize
- iOS: Fixed an issue for passing wrong outputUrl.
> [EPIC-4940] NET DS - Bug Fix and Docs related Changes

- NET/ReadyToUseUI.Droid/Fragments/FilterListFragment.cs
- NET/ReadyToUseUI.iOS/Controller/FilterController.cs
Add some properties to the new filters so that they change when selected in the app (otherwise, half of them have no visual change)
> Change filter properties

- MAUI/ReadyToUseUI.Maui/Pages/HomePage.BarcodeLegacy.xaml.cs
- MAUI/ReadyToUseUI.Maui/Pages/HomePage.DocumentScanner.xaml.cs
- MAUI/ReadyToUseUI.Maui/Pages/HomePage.xaml
- MAUI/ReadyToUseUI.Maui/Pages/HomePage.xaml.cs
- MAUI/ReadyToUseUI.Maui/Pages/ImageDetailPage.cs
- MAUI/ReadyToUseUI.Maui/Pages/ImageResultsPage.cs
- MAUI/ReadyToUseUI.Maui/SubViews/SBLoader.xaml
- MAUI/ReadyToUseUI.Maui/SubViews/SBLoader.xaml.cs
- Created a new custom loader.
- Added it on the Barcode and Document ImagePicking items.
> [EPIC-2954] MAUI DS 5.1 - Added Custom Loader

- MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- MAUI/ReadyToUseUI.Maui/App.xaml.cs
- MAUI/ReadyToUseUI.Maui/Pages/HomePage.BarcodeRTUv2.xaml.cs
- MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- Barcode RTU V2 - Removed the commented code and Replaced the Google links
> MAUI DS 5.1: Replace public links and Remove unused code

- MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- Updated to the latest RC version.
> MAUI DS: Updated RC version

- MAUI/ClassicComponent.Maui/ClassicComponent.Maui.csproj
- MAUI/ReadyToUseUI.Maui/Pages/DetectOnImageResults/DetectOnImageResultPage.xaml
- MAUI/ReadyToUseUI.Maui/Pages/DetectOnImageResults/DetectOnImageResultPage.xaml.cs
- MAUI/ReadyToUseUI.Maui/Pages/HomePage.DetectOnImage.xaml.cs
- MAUI/ReadyToUseUI.Maui/ReadyToUseUI.Maui.csproj
- MAUI/ReadyToUseUI.Maui/Utils/ViewUtils.cs
- Added a View Image page to check the Medica certificate result image. Added a confirmation popup in View utils to display image results .
- Added EHIC status check for result status
- Updated the RC versions
> MAUI DS - Updated RC and Medical Certificate result image

- NET/ReadyToUseUI.Droid/Activities/PagePreviewActivity.cs
- RTU: Replaced Page URI with Document object while Exporting PDF/OCR/TIFF
> [EPIC-5446] NET DS - RTU Droid - Export using Document object

- NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- NET/ReadyToUseUI.Droid/Activities/PagePreviewActivity.Export.cs
- NET/ReadyToUseUI.Droid/Activities/PagePreviewActivity.cs
- NET/ReadyToUseUI.Droid/Fragments/SaveBottomSheetMenuFragment.cs
- NET/ReadyToUseUI.Droid/MainActivity.DataDetector.cs
- NET/ReadyToUseUI.Droid/MainActivity.cs
- NET/ReadyToUseUI.Droid/Model/SaveType.cs
- NET/ReadyToUseUI.Droid/Model/Texts.cs
- NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- NET/ReadyToUseUI.Droid/Resources/layout/save_bottom_sheet.xml
- NET/ReadyToUseUI.iOS/Controller/MainViewController.DataDetectors.cs
- NET/ReadyToUseUI.iOS/Controller/MainViewController.cs
- NET/ReadyToUseUI.iOS/Controller/ScannedDocumentsViewController.Export.cs
- NET/ReadyToUseUI.iOS/Controller/ScannedDocumentsViewController.cs
- NET/ReadyToUseUI.iOS/Models/Texts.cs
- NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
- Fixed a crash for Sandwich PDF in iOS
- Created separate option for Sandwich PDF and Perform OCR.
> [EPIC-5447] NET DS: RTU iOS - Sandwich PDF

- NET/ClassicComponent.Droid/ClassicComponent.Droid.csproj
- NET/ClassicComponent.iOS/ClassicComponent.iOS.csproj
- NET/ReadyToUseUI.Droid/ReadyToUseUI.Droid.csproj
- NET/ReadyToUseUI.iOS/Controller/ScannedDocumentsViewController.Export.cs
- NET/ReadyToUseUI.iOS/ReadyToUseUI.iOS.csproj
- Fixed the Sandwich PDF creation
> NET 6.0 SDK: RTU iOS

- MAUI/ScanbotSdkExample.Maui/Pages/ClassicComponent/ClassicDocumentScannerPage.xaml.cs
- MAUI/ScanbotSdkExample.Maui/Pages/HomePage.DocumentScanner.xaml.cs
- MAUI/ScanbotSdkExample.Maui/Pages/ScannedDocumentsPage.cs
- MAUI/ScanbotSdkExample.Maui/ScanbotSdkExample.Maui.csproj
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/AcknowledgeScreenSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/IntroductionSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/LaunchSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/LocalizationSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/MultiPageSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/PaletteSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/ReorderScreenSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/ReviewScreenSnippets.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/ScanningScreenSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/SinglePageSnippet.cs
- MAUI/ScanbotSdkExample.Maui/Snippets/DocumentScanner/SinglePageWithFinderSnippet.cs
- Updated the Snippets.
- Updated the RC Package Update
- Updated the DocumentDetection Success condition based on the new RTU result wrapper.
> DS MAUI 7.0 

- MAUI/ScanbotSdkExample.Maui/ClassicUI/Pages/ClassicDocumentScannerPage.xaml.cs
- MAUI/ScanbotSdkExample.Maui/Controls/ActionBar/BottomActionBar.cs
- MAUI/ScanbotSdkExample.Maui/HomePage.xaml.cs
- MAUI/ScanbotSdkExample.Maui/Results/ScannedDocumentsPage.cs
- Removed the delete all button from the documents results page and added it on the home page listing in document section. It clears all the document from storage.
- Compressed the document image while previewing
> MAUI DS 7.1.0: 

- Libraries.txt
- MAUI/ScanbotSdkExample.Maui/ClassicUI/MVVM/ViewModels/ClassicDocumentScannerViewModel.cs
- MAUI/ScanbotSdkExample.Maui/ClassicUI/Pages/ClassicDocumentScannerPage.xaml.cs
- Updated the Libraries file
- Updated the Classic DocumentScannerView enum for AutoSnap.
- Fixed the HintLabel when AutoSnapping is turned OFF. (It is hidden now)
> [EPIC-6387] MAUI DS 7.1.0: Minor fixes
